import type { Property } from "@/lib/types"
import { RoomCategory, BedOption, UserRole } from "@/lib/types"
import { mockCategories } from "./categories"

const createMockProperty = (
  id: number,
  tenantId: number,
  name: string,
  categoryId: number,
  description: string,
  location: string,
  latitude: number,
  longitude: number,
  provinsi: string,
  zipCode: string,
  mainImage: string,
  companyName: string,
  managerName: string,
  email: string,
  phone: string,
  rooms: Array<{
    id: number
    name: string
    category: RoomCategory
    description: string
    bedOption: BedOption
    capacity: number
    basePrice: number
  }>,
): Property => ({
  id,
  tenantId,
  name,
  categoryId,
  description,
  location,
  latitude,
  longitude,
  provinsi,
  zipCode,
  mainImage,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
  tenant: {
    id: tenantId,
    userId: tenantId,
    companyName,
    addressCompany: location,
    phoneNumberCompany: phone,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    user: {
      id: tenantId,
      role: UserRole.TENANT,
      fullName: managerName,
      email,
      verified: true,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
  },
  category: mockCategories[categoryId - 1],
  rooms: rooms.map((room) => ({
    ...room,
    propertyId: id,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    property: {} as Property,
  })),
})

export const mockProperties: Property[] = [
  createMockProperty(
    1,
    1,
    "Grand Lodge Downtown",
    1,
    "Luxury hotel in the heart of Jakarta with world-class amenities",
    "Jakarta Pusat",
    -6.2088,
    106.8456,
    "DKI Jakarta",
    "10110",
    "/luxury-downtown-hotel.png",
    "Grand Lodge Management",
    "Hotel Manager",
    "manager@grandlodge.com",
    "+62 21 1234 5678",
    [
      {
        id: 1,
        name: "Standard Room",
        category: RoomCategory.STANDARD,
        description: "Comfortable room with city view",
        bedOption: BedOption.DOUBLE,
        capacity: 2,
        basePrice: 850000,
      },
      {
        id: 2,
        name: "Deluxe Room",
        category: RoomCategory.DELUXE,
        description: "Spacious room with premium amenities",
        bedOption: BedOption.DOUBLE,
        capacity: 3,
        basePrice: 1200000,
      },
    ],
  ),
  createMockProperty(
    2,
    2,
    "Seaside Villa Resort",
    2,
    "Beautiful villa resort with ocean views",
    "Seminyak",
    -8.6905,
    115.1729,
    "Bali",
    "80361",
    "/seaside-villa-resort.png",
    "Seaside Resorts",
    "Villa Manager",
    "manager@seaside.com",
    "+62 361 123456",
    [
      {
        id: 3,
        name: "Ocean View Villa",
        category: RoomCategory.SUITE,
        description: "Luxury villa with private pool and ocean view",
        bedOption: BedOption.DOUBLE,
        capacity: 8,
        basePrice: 2500000,
      },
    ],
  ),
  createMockProperty(
    3,
    3,
    "Mountain View Lodge",
    3,
    "Cozy lodge with stunning mountain views",
    "Lembang",
    -6.8116,
    107.6178,
    "Jawa Barat",
    "40391",
    "/mountain-view-lodge.png",
    "Mountain Lodge Co",
    "Lodge Manager",
    "manager@mountainlodge.com",
    "+62 22 123456",
    [
      {
        id: 4,
        name: "Mountain Cabin",
        category: RoomCategory.STANDARD,
        description: "Rustic cabin with mountain view",
        bedOption: BedOption.TWIN,
        capacity: 4,
        basePrice: 650000,
      },
    ],
  ),
  createMockProperty(
    4,
    4,
    "Urban Boutique Hotel",
    1,
    "Modern boutique hotel in the city center",
    "Surabaya Pusat",
    -7.2575,
    112.7521,
    "Jawa Timur",
    "60271",
    "/urban-boutique-hotel.png",
    "Urban Hotels",
    "Hotel Manager",
    "manager@urbanhotel.com",
    "+62 31 123456",
    [
      {
        id: 5,
        name: "Boutique Room",
        category: RoomCategory.DELUXE,
        description: "Stylish room with modern amenities",
        bedOption: BedOption.DOUBLE,
        capacity: 2,
        basePrice: 750000,
      },
    ],
  ),
]

export { createMockProperty }
